#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}-front" --action="stop" --log_path="/var/log/$app/${app}-front.log"
ynh_systemctl --service="${app}-back" --action="stop" --log_path="/var/log/$app/${app}-back.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# ...
#=================================================
ynh_config_add --template="front.env" --destination="$install_dir/frontend/.env.local"
ynh_config_add --template="back.env" --destination="$install_dir/api/.env"

# Next.js copies some env values inside the
# production build so we have to rebuild it

build_frontend

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}-front" --action="start" --log_path="/var/log/$app/${app}-front.log"
ynh_systemctl --service="${app}-back" --action="start" --log_path="/var/log/$app/${app}-back.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
