#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add --template="crabfit.target" --destination="/etc/systemd/system/$app.target"
ynh_config_add_systemd --service="${app}-front" --template="crabfit-front.service"
ynh_config_add_systemd --service="${app}-back" --template="crabfit-back.service"

yunohost service add "${app}-front" --description="Crabfit NodeJS Frontend" --log="/var/log/$app/${app}-front.log"
yunohost service add "${app}-back" --description="Crabfit Rust Backend" --log="/var/log/$app/${app}-back.log"

ynh_config_add_logrotate

#=================================================
# ADD CONFIGURATIONS
#=================================================
ynh_script_progression "Adding configuration files..."

# Replace the default .env.local with our own
rm $install_dir/frontend/.env.local
ynh_config_add --template="front.env" --destination="$install_dir/frontend/.env.local"

ynh_config_add --template="back.env" --destination="$install_dir/api/.env"

#=================================================
# BUILD BACKEND
#=================================================
ynh_script_progression "Building crabfit backend..."

build_backend

#=================================================
# BUILD FRONTEND
#=================================================
ynh_script_progression "Building crabfit frontend..."

build_frontend

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd services..."

# Start a systemd service
ynh_systemctl --service="${app}-front" --action="start" --log_path="/var/log/$app/${app}-front.log"
ynh_systemctl --service="${app}-back" --action="start" --log_path="/var/log/$app/${app}-back.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
