#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
ynh_script_progression "Removing $app service integration..."
yunohost service remove "${app}-back"
yunohost service remove "${app}-front"

ynh_config_remove_systemd "${app}-back"
ynh_config_remove_systemd "${app}-front"
ynh_safe_rm "/etc/systemd/system/$app.target"

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
